name: Build
permissions: write-all

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: '.xmake-cache'
        actions-cache-key: 'ci'
    
    - name: build
      run: |
        xmake c -m releasedbg
        xmake f --toolchain=clang-cl
        xmake b -y --verbose inject
        xmake b -y --verbose shell

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        path: ./build/windows/

    - name: Create Archive
      if: github.event_name == 'release'
      run: |
        Compress-Archive -Path ./build/windows/* -DestinationPath windows-build.zip

    - name: Upload Release Assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: windows-build.zip
        token: ${{ secrets.GITHUB_TOKEN }}
